all: learning

learning: learning.cpp
	g++ -g -Wall -std=c++11 learning.cpp -o learning

all: doublet

doublet: doublet.cpp
	g++ -g -Wall -std=c++11 doublet.cpp -o doublet

all: heap

heap: main.cpp heap.h
	g++ -g -Wall -std=c++11 main.cpp -o heap